### ISSUE TITLE
Plugin doesn't seem to work.

### ISSUE THREAD

**Issue by ghost** [john01dav/sqlperms-2.0-testing#1]
9.12 07:28:30 [Server] INFO ... 10 more
29.12 07:28:30 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[Spigot18.jar:git-Spigot-"609cd55"]
29.12 07:28:30 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_55]
29.12 07:28:30 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
29.12 07:28:30 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
29.12 07:28:30 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_55]
29.12 07:28:30 [Server] INFO at src.john01dav.sqlperms.permissions.PermissionsListener.playerChatEvent(PermissionsListener.java:51) ~[?:?]
29.12 07:28:30 [Server] INFO Caused by: java.lang.NullPointerException
29.12 07:28:30 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_55]
29.12 07:28:30 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:528) [Spigot18.jar:git-Spigot-"609cd55"]
29.12 07:28:30 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:625) [Spigot18.jar:git-Spigot-"609cd55"]
29.12 07:28:30 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [Spigot18.jar:git-Spigot-"609cd55"]
29.12 07:28:30 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:701) [Spigot18.jar:git-Spigot-"609cd55"]
29.12 07:28:30 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.util.Waitable.run(Waitable.java:24) [Spigot18.jar:git-Spigot-"609cd55"]
29.12 07:28:30 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection$4.evaluate(PlayerConnection.java:1013) [Spigot18.jar:git-Spigot-"609cd55"]
29.12 07:28:30 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [Spigot18.jar:git-Spigot-"609cd55"]
29.12 07:28:30 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [Spigot18.jar:git-Spigot-"609cd55"]
29.12 07:28:30 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot18.jar:git-Spigot-"609cd55"]
29.12 07:28:30 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[Spigot18.jar:git-Spigot-"609cd55"]
29.12 07:28:30 [Server] INFO org.bukkit.event.EventException
29.12 07:28:30 [Server] ERROR Could not pass event PlayerChatEvent to SQLPerms v2.0 Closed Beta

**Comment by john01dav** [comment]
Could you pastebin this and/or put it in code tags?

**Comment by ghost** [comment]
http://pastebin.com/XDpY6UKS

**Comment by john01dav** [comment]
What triggers this error?

**Comment by john01dav** [comment]
Ok, it seems to be working for others. I'm closing this issue.
